
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  category text,
  image_url text,
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  address text not null,
  city text,
  total numeric not null,
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Order Items Table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references products(id),
  product_name text,
  quantity integer not null,
  price numeric not null
);

-- Seed Data (Optional)
insert into products (name, category, price, image_url) values
('Traditional Bamboo Basket', 'Handicrafts', 75000, '/assets/product-basket.png'),
('Local Coffee Beans', 'Food', 45000, '/assets/product-coffee.png');

-- STORAGE SETUP
-- Run this part if you see "Bucket not found" errors
-- (Ensure you run only this part if your tables already exist)

-- 1. Create Bucket
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'products' );

DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'products' AND auth.role() = 'authenticated' );

